import { icons } from "./icons";

export const tabs: AppTab[] = [
    { name: "index", title: "Home", icon: icons.home },
    { name: "subscriptions", title: "Subscriptions", icon: icons.wallet },
    { name: "insights", title: "Insights", icon: icons.activity },
    { name: "settings", title: "Settings", icon: icons.setting },
];

export const HOME_USER = {
    name: "Adrian | JS Mastery",
};

export const HOME_BALANCE = {
    amount: 2489.48,
    nextRenewalDate: "2026-03-18T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
    {
        id: "spotify",
        icon: icons.spotify,
        name: "Spotify",
        price: 5.99,
        currency: "USD",
        daysLeft: 2,
    },
    {
        id: "notion",
        icon: icons.notion,
        name: "Notion",
        price: 12.0,
        currency: "USD",
        daysLeft: 4,
    },
    {
        id: "figma",
        icon: icons.figma,
        name: "Figma",
        price: 15.0,
        currency: "USD",
        daysLeft: 6,
    },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = [
    {
        id: "adobe-creative-cloud",
        icon: icons.adobe,
        name: "Adobe Creative Cloud",
        plan: "Teams Plan",
        category: "Design",
        paymentMethod: "Visa ending in 8530",
        status: "active",
        startDate: "2025-03-20T10:00:00.000Z",
        price: 77.49,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-20T10:00:00.000Z",
        color: "#f5c542",
    },
    {
        id: "github-pro",
        icon: icons.github,
        name: "GitHub Pro",
        plan: "Developer",
        category: "Developer Tools",
        paymentMethod: "Mastercard ending in 2408",
        status: "active",
        startDate: "2024-11-24T10:00:00.000Z",
        price: 9.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-24T10:00:00.000Z",
        color: "#e8def8",
    },
    {
        id: "claude-pro",
        icon: icons.claude,
        name: "Claude Pro",
        plan: "Pro Plan",
        category: "AI Tools",
        paymentMethod: "Amex ending in 1010",
        status: "paused",
        startDate: "2025-06-27T10:00:00.000Z",
        price: 20.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-27T10:00:00.000Z",
        color: "#b8d4e3",
    },
    {
        id: "canva-pro",
        icon: icons.canva,
        name: "Canva Pro",
        plan: "Yearly Access",
        category: "Design",
        paymentMethod: "Visa ending in 7784",
        status: "cancelled",
        startDate: "2024-04-02T10:00:00.000Z",
        price: 119.99,
        currency: "USD",
        billing: "Yearly",
        renewalDate: "2026-04-02T10:00:00.000Z",
        color: "#b8e8d0",
    },
];

export const ALL_SUBSCRIPTIONS: Subscription[] = [
    {
        id: "dropbox",
        icon: icons.dropbox,
        name: "Dropbox",
        plan: "Premium",
        category: "Cloud Storage",
        paymentMethod: "*****4242",
        status: "active",
        startDate: "2024-01-15T10:00:00.000Z",
        price: 16.96,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-15T10:00:00.000Z",
    },
    {
        id: "spotify",
        icon: icons.spotify,
        name: "Spotify",
        plan: "Family Plan",
        category: "Entertainment",
        paymentMethod: "*****1234",
        status: "active",
        startDate: "2024-06-10T10:00:00.000Z",
        price: 76.77,
        currency: "USD",
        billing: "3 months",
        renewalDate: "2026-05-10T10:00:00.000Z",
    },
    {
        id: "github-copilot",
        icon: icons.github,
        name: "GitHub Copilot",
        plan: "Pro Business",
        category: "Developer Tools",
        paymentMethod: "*****8530",
        status: "active",
        startDate: "2024-11-24T10:00:00.000Z",
        price: 49.99,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-24T10:00:00.000Z",
    },
    {
        id: "adobe",
        icon: icons.adobe,
        name: "Adobe",
        plan: "Family Plan",
        category: "Design",
        paymentMethod: "*****8530",
        status: "active",
        startDate: "2024-04-20T10:00:00.000Z",
        price: 98.10,
        currency: "USD",
        billing: "2 months",
        renewalDate: "2026-04-20T10:00:00.000Z",
    },
    {
        id: "figma",
        icon: icons.figma,
        name: "Figma",
        plan: "Premium",
        category: "Design",
        paymentMethod: "*****9012",
        status: "active",
        startDate: "2024-08-19T10:00:00.000Z",
        price: 19.23,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-19T10:00:00.000Z",
    },
    {
        id: "claude-pro",
        icon: icons.claude,
        name: "Claude Pro",
        plan: "Pro Plan",
        category: "AI Tools",
        paymentMethod: "*****1010",
        status: "paused",
        startDate: "2025-06-27T10:00:00.000Z",
        price: 20.0,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-27T10:00:00.000Z",
    },
    {
        id: "notion",
        icon: icons.notion,
        name: "Notion",
        plan: "Plus Plan",
        category: "Productivity",
        paymentMethod: "*****5543",
        status: "active",
        startDate: "2024-02-12T10:00:00.000Z",
        price: 12.0,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-22T10:00:00.000Z",
    },
    {
        id: "canva-pro",
        icon: icons.canva,
        name: "Canva Pro",
        plan: "Yearly Access",
        category: "Design",
        paymentMethod: "*****7784",
        status: "cancelled",
        startDate: "2024-04-02T10:00:00.000Z",
        price: 119.99,
        currency: "USD",
        billing: "Yearly",
        renewalDate: "2026-04-02T10:00:00.000Z",
    },
    {
        id: "netflix",
        icon: icons.netflix,
        name: "Netflix",
        plan: "Premium 4K",
        category: "Entertainment",
        paymentMethod: "*****4921",
        status: "active",
        startDate: "2023-09-15T10:00:00.000Z",
        price: 22.99,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-15T10:00:00.000Z",
    },
    {
        id: "openai",
        icon: icons.openai,
        name: "ChatGPT Plus",
        plan: "Plus",
        category: "AI Tools",
        paymentMethod: "*****3321",
        status: "active",
        startDate: "2024-03-10T10:00:00.000Z",
        price: 20.0,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-03-10T10:00:00.000Z",
    },
    {
        id: "medium",
        icon: icons.medium,
        name: "Medium",
        plan: "Member",
        category: "Reading",
        paymentMethod: "*****6642",
        status: "active",
        startDate: "2024-05-01T10:00:00.000Z",
        price: 5.0,
        currency: "USD",
        billing: "1 month",
        renewalDate: "2026-04-01T10:00:00.000Z",
    },
];